#!/usr/bin/env bash
# auto-handoff.sh — Safety-net HANDOFF.md update from observable git state.
# Called by the Claude Code Stop hook. Safe to run frequently — skips when
# nothing has changed in the working tree.

set -euo pipefail

# Must be inside a git repo
git rev-parse --git-dir &>/dev/null || exit 0

HANDOFF="$(pwd)/HANDOFF.md"
TIMESTAMP=$(date "+%Y-%m-%d %H:%M")
BRANCH=$(git branch --show-current 2>/dev/null || echo "detached")
MODIFIED=$(git status --short 2>/dev/null)

# Nothing uncommitted — nothing worth capturing
[ -z "$MODIFIED" ] && exit 0

RECENT_COMMITS=$(git log --oneline -5 2>/dev/null || echo "none")

TICKETS=""
if command -v tk &>/dev/null; then
  TICKETS=$(tk ls --status=in_progress 2>/dev/null | head -10 || true)
fi

SNAPSHOT="

---
## Auto-snapshot — $TIMESTAMP (branch: $BRANCH)
> Auto-generated by Stop hook. Manually update Current Focus and Decisions above for full context.

**Modified files:**
\`\`\`
$MODIFIED
\`\`\`

**Recent commits:**
\`\`\`
$RECENT_COMMITS
\`\`\`"

if [ -n "$TICKETS" ]; then
  SNAPSHOT="$SNAPSHOT

**In-progress tickets:**
\`\`\`
$TICKETS
\`\`\`"
fi

if [ -f "$HANDOFF" ]; then
  # Strip any previous auto-snapshot block and append a fresh one
  CONTENT=$(awk '
    /^---$/ && found_snapshot { in_snapshot=1 }
    /^## Auto-snapshot/ { found_snapshot=1 }
    !in_snapshot { print }
    in_snapshot && /^$/ && prev_blank { in_snapshot=0; found_snapshot=0 }
    { prev_blank=(/^$/) }
  ' "$HANDOFF" 2>/dev/null || cat "$HANDOFF")
  printf '%s\n%s\n' "$CONTENT" "$SNAPSHOT" > "$HANDOFF"
else
  cat > "$HANDOFF" << EOF
# Handoff

_Auto-created: $TIMESTAMP | Branch: $BRANCH_

## Current Focus
<!-- One sentence: what were you working on? Fill this in. -->

## In Progress
$([ -n "$TICKETS" ] && echo "$TICKETS" || echo "- (run \`tk ls --status=in_progress\` to check)")

## Recent Decisions
-

## Dead Ends
-

## Next Steps
1.
$SNAPSHOT
EOF
fi

# Commit just HANDOFF.md — gracefully skip if hooks block it or nothing to commit
git add "$HANDOFF" 2>/dev/null || true
git commit -m "Auto-update handoff snapshot [$TIMESTAMP]" 2>/dev/null || true

echo "[handoff] Snapshot saved → HANDOFF.md"
